### PR TITLE
Add a basic CLI

### PR DESCRIPTION
**Pull request by cidrblock**
- Add a basic CLI, `search` only
- Add output in either json or table
- Include addiitonal formats in the tunein search
- Update gitiginore to include venv

Thanks for this, it came in handy.

Brad

### CODE REVIEW

**Comment by JarbasAl** [comment]
thanks for the PR! I like what I see, will try to give it a spin soon

**Comment by cidrblock** [comment]
I realized with the addition of the additional stream types the one picked is not determinisitic.  I will have a follow on PR to expose multiple streams, their media type and bit rate.  This one was already a little loose in scope.

**Comment by emphasize** [comment]
It would need adjustments in setup.py if handled like that
```
packages=["tunein", "tunein/subcommands"],
```

```
# tunein search "Milano Lounge"
Traceback (most recent call last):
  File "/home/ovos/vovos/bin/tunein", line 5, in <module>
    from tunein.cli import main
  File "/home/ovos/vovos/lib/python3.10/site-packages/tunein/cli.py", line 5, in <module>
    from tunein import subcommands
ImportError: cannot import name 'subcommands' from 'tunein' (/home/ovos/vovos/lib/python3.10/site-packages/tunein/__init__.py)
```

**Comment by emphasize** [comment]
Please add - even though the README is a blank slate - a few words about the cli tool

**Review by emphasize — APPROVED** [review]

**Comment by cidrblock** [comment]
@emphasize Do you have a minute to approve the workflows to see if the tests pass with the setup changes now?

**Pull request merged**
